### ISSUE TITLE
Add fullpath attribute to Spectrum Node

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/spectrum#13]
This is necessary to implement a delete functionality.

**Comment by k9ert** [comment]
AFAIK the fullpath should also be in there. So if it's not, than that'd be a bug.
https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/managers/node_manager.py#L246-L250

**Comment by moneymanolis** [comment]
The spectrum node doesn't have a fullpath attribute and the line you cited in the node manager is not setting it.

**Comment by k9ert** [comment]
fixed
