### ISSUE TITLE
Change wording in beta version feedback

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/spectrum#14]
![grafik](https://user-images.githubusercontent.com/70536101/204820617-2f3f15f2-dc52-4ef9-84cf-ee86739d2546.png)

It's currently not possible to delete the Bitcoin Core node if it is the only node. So, perhaps better to write ""Disconnect the Bitcoin Core node"?

**Comment by moneymanolis** [comment]
There is no front end functionality yet in Specter Desktop to disconnect a node, though. @k9ert Does it make sense to add this in Specter Desktop, what do you think?

**Comment by k9ert** [comment]
Yes, definitely!
