### ISSUE TITLE
Wallet manager needs to be refactored to use Spectrum node alongside Core node

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/spectrum#15]
Gathering some problems / errors of the status quo in this issue:

**1) Loadwallet error**
- Creating a wallet while using Spectrum generates a JSON file but doesn't save the wallet file on the Core node (obviously) since it uses the database to store the wallet data.
- Therefore, when you switch back to using the Core node you get this error:

<img width="602" alt="grafik" src="https://user-images.githubusercontent.com/70536101/204830605-a7df0283-6691-4fea-b181-9d03f35b51a4.png">

**Comment by k9ert** [comment]
closing this. It'll be discussed/addressed on #34
