### ISSUE TITLE
Hot wallet not implemented (correctly)

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/spectrum#20]
Created a hot wallet but in the wallet table in the database it shows for the wallet `private keys enabled 0` and there is no seed.
When trying to sign a tx with the hot wallet, I get:

![grafik](https://user-images.githubusercontent.com/70536101/205505037-4cdcc4ec-3482-4ea9-b8c2-93cdc5c571d7.png)

**Comment by k9ert** [comment]
Won't fix. No hotwallet support in Spectrum.
