### ISSUE TITLE
No transactions and wrong balance shown

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/spectrum#26]
Unknown method "gettxoutproof"

![image](https://user-images.githubusercontent.com/70536101/206453889-2dbd9989-9112-4820-b92d-efb26dbcefaa.png)

**Comment by k9ert** [comment]
This is most probably due to "validate merke proofs". A workyround MIGHT be to turn it off.
![image](https://user-images.githubusercontent.com/117085/206456385-b704a59f-a540-4ddb-a87b-8053e9dba4b5.png)

**Comment by moneymanolis** [comment]
Yes, I could reproduce it with that.

**Comment by k9ert** [comment]
fixed
