### ISSUE TITLE
Forget node functionality is missing

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/spectrum#27]
Could be integrated here on this screen. "Forget node" button only if there is a Spectrum node already configured.
With sth. like:
`app.specter.node_manager.delete_node(node, app.specter)`

<img width="560" alt="image" src="https://user-images.githubusercontent.com/70536101/206462714-5858ff92-28aa-44d4-a872-8385bd07888c.png">

Needs this issue to be done first:
https://github.com/cryptoadvance/spectrum/issues/13

**Comment by k9ert** [comment]
In the work here: 
https://github.com/cryptoadvance/specter-desktop/pull/2047

**Comment by k9ert** [comment]
merged, closing here.
