### ISSUE TITLE
Implement getrawtransaction

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/spectrum#33]
This is needed for the whitepaper functionality in Specter.
https://github.com/cryptoadvance/specter-desktop/issues/2065

**Comment by k9ert** [comment]
@PaarthAgarwal  maybe this is something you're interested in? Here are some infos to have more context:
* https://developer.bitcoin.org/reference/rpc/getrawtransaction.html
* https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-get this is the API on the electrum side and chances are high that it delivers exactly what is needed.
* As this is not a bitcoin wallet-API i'd implement if e.g. here: https://github.com/cryptoadvance/spectrum/blob/master/src/cryptoadvance/spectrum/spectrum.py#L543

Have a look how the electrum API is called and it's probably quite simple to implement it here.

**Comment by PaarthAgarwal** [comment]
Going through the references. I think I should be able to implement it
